import Close from "../../assets/otherIcons/close.svg";
import Edit from "../../assets/otherIcons/edit.svg";
import Trash from "../../assets/otherIcons/trash.svg";
import Timer from "../../assets/otherIcons/timer.svg";
import Tag from "../../assets/otherIcons/tag.svg";
import Flag from "../../assets/otherIcons/flag.svg";
import Grocery from "../../assets/categoriesIcon/grocery.svg";
import Health from "../../assets/categoriesIcon/health.svg";
import Home from "../../assets/categoriesIcon/home.svg";
import Movie from "../../assets/categoriesIcon/movie.svg";
import Music from "../../assets/categoriesIcon/music.svg";
import Social from "../../assets/categoriesIcon/social.svg";
import Sport from "../../assets/categoriesIcon/sport.svg";
import University from "../../assets/categoriesIcon/university.svg";
import Work from "../../assets/categoriesIcon/work.svg";
import Design from "../../assets/categoriesIcon/design.svg";
import HomeBar from "../../assets/otherIcons/home.svg";
import HomeBarFocused from "../../assets/otherIcons/homeFocused.svg";
import Repeat from "../../assets/otherIcons/repeat.svg";
import Add from "../../assets/otherIcons/add.svg";
import Search from "../../assets/otherIcons/search.svg";
import ArrowDown from "../../assets/otherIcons/arrowDown.svg";
import User from "../../assets/otherIcons/user.svg";
import UserFocused from "../../assets/otherIcons/userFocused.svg";
import Calendar from "../../assets/otherIcons/calendar.svg";
import CalendarFocused from "../../assets/otherIcons/calendarFocused.svg";
import Clock from "../../assets/otherIcons/clock.svg";
import ClockFocused from "../../assets/otherIcons/clockFocused.svg";
import Send from "../../assets/otherIcons/send.svg";
import SendDisabled from "../../assets/otherIcons/sendDisabled.svg";

export const CloseIcon = Close.toString();
export const EditIcon = Edit.toString();
export const TrashIcon = Trash.toString();
export const TimerIcon = Timer.toString();
export const TagIcon = Tag.toString();
export const FlagIcon = Flag.toString();
export const DesignIcon = Design.toString();
export const GroceryIcon = Grocery.toString();
export const HealthIcon = Health.toString();
export const HomeIcon = Home.toString();
export const MovieIcon = Movie.toString();
export const MusicIcon = Music.toString();
export const SocialIcon = Social.toString();
export const SportIcon = Sport.toString();
export const UniversityIcon = University.toString();
export const WorkIcon = Work.toString();
export const HomeBarIcon = HomeBar.toString();
export const HomeBarFocusedIcon = HomeBarFocused.toString();
export const RepeatIcon = Repeat.toString();
export const AddIcon = Add.toString();
export const SearchIcon = Search.toString();
export const ArrowDownIcon = ArrowDown.toString();
export const UserIcon = User.toString();
export const UserFocusedIcon = UserFocused.toString();
export const CalendarIcon = Calendar.toString();
export const CalendarFocusedIcon = CalendarFocused.toString();
export const ClockIcon = Clock.toString();
export const ClockFocusedIcon = ClockFocused.toString();
export const SendIcon = Send.toString();
export const SendDisabledIcon = SendDisabled.toString();
